### PR TITLE
Varuns branch

### PR DESCRIPTION
**Pull request by vb1262**

### CODE REVIEW

**Comment by techsupport-2006** [comment]
Having Issues merging - says there are unexpected tokens in your ClipboardContainer.js file. Not sure if its only on my end.

**Comment by Larry-Langman** [comment]
@vb1262 Put cliboard container into the app folder, where all our app views are stored so we can access it from the app.js file like all the other screens.

**Comment by vb1262** [comment]
I fixed the issue it works on mobile now, just need to do mockaroo w/ Whitney (had a little trouble by myself)

**Comment by vb1262** [comment]
@Larry-Langman  fixed the issue, should be good to go now

**Comment by vb1262** [comment]
@Larry-Langman if you got mockaroo working could we sit down and go through it once, am having trouble getting that part

**Comment by Larry-Langman** [comment]
honestly not sure about mockaroo, cuz i don't need fake data for the login screen

**Pull request merged**
